services:
  - type: web
    name: piosenki-api
    runtime: python
    rootDir: piosenki
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TURSO_DATABASE_URL
        value: libsql://happy-hue-octopus-maciek-hue.aws-eu-west-1.turso.io
      - key: TURSO_ADMIN_TOKEN
        sync: false
