services:
  - type: web
    name: piosenki-api
    runtime: python
    rootDir: piosenki
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn content_explorer_app:app
    envVars:
      - key: SUPABASE_DATABASE_URL
        sync: false
