import csv
from pathlib import Path

SRC = Path('rosja/SOL_mapa-sekcji-i-anchorow-rosja.tsv')
OUT = Path('rosja/SOL_mapa-sekcji-z-opisami-bez-A1.tsv')

MANUAL = {
    ('A2', 'dokument-o-dokumencie'): 'Zmiana z kroniki uderzeń w analizę systemowego rozkładu.',
    ('A2', 'dekret-dron-tarcza'): 'Usunięcie cywilów z R-280 jako wymuszona rezygnacja z tarczy.',
    ('A2', 'krym-efekt-zewnetrzny'): 'Izolacja Krymu jako skutek uboczny szerszej kampanii logistyczno-naftowej.',
    ('A2', 'krym-watki-kontynuowane'): 'Odsyłacze do dalszych analiz Krymu: sygnalizacja, paliwa i energetyka.',
    ('A2', 'front-olexandrivka-uzasadnienie'): 'Olexandrivka jako materialny skutek degradacji rosyjskiej logistyki i OPL.',
    ('A2', 'negative-space-metoda'): 'Czytanie nieobecności jako danych: brak słów, działań i dostaw.',
    ('A2', 'zmiana-ilosciowa'): 'Wykładniczy wzrost liczby, częstotliwości i zasięgu ukraińskich uderzeń.',
    ('A2', 'zmiana-jakosciowa'): 'Rozszerzenie kampanii z rafinerii na logistykę, Krym, sygnalizację i rynek paliw.',
    ('A2', 'lista-uderzen'): 'Kotwica po wydzieleniu pełnej kroniki uderzeń do osobnego pliku.',
    ('A2', 'nota-metodologiczna'): 'Wariantowe wnioskowanie przy nieznanych danych, bez zgadywania brakujących zmiennych.',
    ('A2', 'galeria-celow'): 'Wybrane uderzenia jako przykłady mechanizmów i logiki całej kampanii.',
    ('A2', 'cele-niekinetyczne'): 'Presja na percepcję, dowodzenie i morale zamiast wyłącznie celów fizycznych.',
    ('A2', 'krym-efekt-uboczny'): 'Izolacja Krymu jako produkt uboczny kampanii przeciw logistyce i energii.',
    ('A2', 'trzy-wektory'): 'Lądowy, morski i mostowy kanał zaopatrzenia Krymu oraz ich degradacja.',
    ('A2', 'r280-tarcza'): 'Usunięcie cywilów z R-280 jako wymuszony kompromis logistyczny Rosji.',
    ('A2', 'most-przyneta'): 'Nietknięty Most Kerczeński wiąże rosyjską OPL i odsłania inne cele.',
    ('A2', 'most-poker-meta'): 'Trzy strategie wobec mostu: wcześniej, na finał albo permanentne ciśnienie.',
    ('A2', 'krym-darmowy'): 'Odcięcie portów Krymu przez uderzanie w rosyjski koniec szlaku morskiego.',
    ('A2', 'morza-drugi-koniec'): 'Porty rosyjskie i okupowane jako węzły morskiego łańcucha zaopatrzenia.',
    ('A2', 'morza-czarne'): 'Czarnomorskie porty Krasnodaru obsługujące eksport i logistykę wojenną.',
    ('A2', 'morza-azowskie-ru'): 'Rosyjskie porty azowskie jako drugi koniec łańcucha logistycznego.',
    ('A2', 'morza-azowskie-okup'): 'Mariupol i Berdiańsk jako okupowane węzły przeładunkowe na Morzu Azowskim.',
    ('A2', 'krym-wyspa'): 'Stopniowa utrata połączeń zamienia Krym w wyspę logistyczną.',
    ('A2', 'krym-odcinanie-pradu'): 'Energetyka jako czwarty, równoległy wektor izolowania Krymu.',
    ('A2', 'krym-kupony'): 'Reglamentacja paliwa jako materialny objaw narastającej izolacji półwyspu.',
    ('A2', 'ewolucja-typologii'): 'Jak kampania rozszerza się na nowe klasy celów i nowe teatry.',
    ('A2', 'matryca-kategorie'): 'Zmiany aktywnych kategorii celów od stycznia do czerwca 2026.',
    ('A2', 'matryca-geograficzna'): 'Przesuwanie kampanii między Bałtykiem, południem, centrum, Uralem i okupacją.',
    ('A2', 'synteza-ewolucyjna'): 'Pięć jakościowych progów dojrzewania kampanii od stycznia do czerwca.',
    ('A2', 'syntetyczne-obserwacje'): 'Najważniejsze wzorce: zasięg, dywersyfikacja, kompresja napraw i przeciążenie OPL.',
    ('A2', 'front-olexandrivka'): 'Odzyskiwane terytorium jako nowa kategoria skutku kampanii systemowej.',
    ('A2', 'wstep-jakosciowa-zmiana'): 'Od monografii rafinerii do sekwencyjnej analizy systemowego rozkładu Rosji.',
    ('A2', 'budanov-negative-space'): 'Zmiana słownika Budanowa: mniej „zwycięstwa”, więcej jedności i ryzyk wewnętrznych.',
    ('A2', 'punkt-zwrotny-za-wczesnie'): 'Prognoza z 2022 kierunkowo trafna, lecz przedwczesna o około cztery lata.',
    ('A2', 'budanov-nieliniowa'): 'Sprzeczne stany traktowane jako równocześnie prawdziwe, bez binarnego wyboru.',
    ('A2', 'stoicyzm-maska-operacyjna'): '„Stoicyzm” jako użyteczna maska dla nieliniowego sposobu działania Budanowa.',
    ('A2', 'budanov-regfrom'): 'Rozumienie reguł pozwala tworzyć nowe kategorie zamiast tylko je łamać.',
    ('A2', 'budanov-jednosc'): 'Jedność sytuacyjna jako zdolność wspólnej decyzji, nie permanentne posłuszeństwo.',
    ('A2', 'antifragile-dark-legitimacy'): 'Ukraińska jedność jako antykruchość przeciw rosyjskiej dark legitimacy.',
    ('A2', 'po-tupolewa-do-sklepu'): 'Nieodtwarzalne platformy sowieckie: każda strata trwale zmniejsza dostępny zasób.',
    ('A2', 'uwaga-a50-precedens'): 'Dwa utracone A-50 jako precedens nieodtwarzalnej degradacji zdolności AWACS.',
    ('A2', 'mapa-dniepr-trzy-warstwy'): 'Mapa Dniepr pokazuje trzy warstwy fałszowania obrazu frontu wewnątrz systemu.',
    ('A2', 'saldo-leningrad-autodemaskacja'): 'Propagandowa metafora Saldo mimowolnie potwierdza izolację rosyjskiej logistyki.',
    ('A2', 'voenkory-pekaja'): 'Rozszczepienie rosyjskich milblogerów jako sygnał pękania dyscypliny narracyjnej.',
    ('A2', 'sokolenko-prosil-nie-obwiniac'): 'Komunikat o śmierci Sokolenki analizowany przez gramatykę przemilczeń i formułkę winy.',
    ('A2', 'tradycja-rosyjskiego-samobojstwa'): 'Sokolenko wpisany w szerszy wzorzec niewyjaśnionych śmierci rosyjskich elit.',
    ('A2', 'budanov-838'): 'Precyzyjna liczba zabitych oficerów jako narzędzie wiarygodności i presji.',
    ('A2', 'budanov-neurodywergencja'): 'Hipoteza neurodywergencji jako źródła wzorców poznawczych użytecznych w wywiadzie.',
    ('A2', 'budanov-gramatyka'): 'Budanow jako rama do czytania rozkładu Rosji, informacji i ukraińskiej przebudowy.',
    ('A2', 'zalozenia-metodologiczne'): 'Profesjonalna komunikacja wieloadresatowa: nadawca projektuje możliwe interpretacje odbiorców.',
    ('A2', 'studium-przemowienie'): 'Wypowiedź Zełenskiego z 17 maja jako sygnał dojrzałej zdolności dalekiego zasięgu.',
    ('A2', 'komunikat-wieloadresatowy'): 'Ta sama wypowiedź czytana inaczej przez Ukrainę, Rosję, Pekin i korporacje.',
    ('A2', 'sekwencja-commit'): 'Najpierw zobowiązania polityczne, potem demonstracja zdolności dla maksymalnej wartości sygnału.',
    ('A2', 'logika-wstrzymaj-pokaz'): 'Umowy przed demonstracją zwiększają nadwartość i legitymizują wybór partnerów.',
    ('A2', 'sygnaly-wstrzymania'): 'Ślady kontroli rytmu: dobór amunicji, selektywna pauza i ukrywanie maksimum.',
    ('A2', 'alternatywa-lipiec'): 'Maj politycznie przyspiesza operacyjny plan letni po szoku wojny w Iranie.',
    ('A2', 'trzydniowa-kampania'): 'Tygodniowa kampania ujawnienia zdolności, wywiadu, broni, doktryny i oczekiwań.',
    ('A2', 'obserwacje-strukturalne'): 'Wiele kanałów i nadawców jako ślad skoordynowanej kampanii komunikacyjnej.',
    ('A2', 'druga-kampania-bialoruska'): 'Białoruś jako oś zsynchronizowanej kampanii dyplomatycznej, odstraszającej i sankcyjnej.',
    ('A2', 'krym-wyspa-logistyczna'): 'Korytarz lądowy do Krymu przechodzi od degradacji do faktycznej utraty funkcji.',
    ('A2', 'europejska-os-instytucjonalna'): 'UE formalizuje warunki wobec Rosji i wzmacnia ukraińską ramę nacisku.',
    ('A2', 'test-dyplomatyczny-kijow'): 'Obecność zagranicznych dyplomatów w Kijowie jako test gotowości do ponoszenia ryzyka.',
    ('A2', 'galati-rumunia-nato'): 'Rosyjski dron w Rumunii jako test granicy między incydentem a odpowiedzią NATO.',
    ('A2', 'gabala-aliyev-mediator'): 'Aliyev jako alternatywny mediator dzięki rosnącej autonomii Azerbejdżanu od Moskwy.',
    ('A2', 'cztery-przegrane-wybory'): 'Seria porażek politycznych jako osobny front erozji rosyjskich wpływów.',
    ('A2', 'asymetria-katalogow-celow'): 'Kontrast legalności celów i przejęcie przez Ukrainę ramy rozejmowo-sankcyjnej.',
    ('A2', 'long-range-sanctions-doktryna'): '„Long-range sanctions” jako nazwana polityczna rama ukraińskich uderzeń głębokich.',
    ('A2', 'dwa-procesy-a-b'): 'Dwa niezależne procesy: degradacja frontu dziś i strangulacja gospodarki jutro.',
    ('A2', 'nyquist-dwa-procesy'): 'Nakładanie dwóch rytmów uderzeń przeciąża rosyjski cykl obserwacji i reakcji.',
    ('A2', 'dwadziescia-miliardow'): 'Koszt kampanii liczony jako osiągalna, podzielna inwestycja strategiczna Ukrainy.',
    ('A2', 'p1-sun-tania-asymetria-obronna'): 'Tania asymetria dronowa odwrócona z ataku na ochronę ukraińskich celów.',
    ('A2', 'kubanska-anomalia-historyczna'): 'Kubań jako problem dla rosyjskiej narracji historycznej i doktryny Russkij Mir.',
    ('A2', 'moskwa-tonie-co-lato'): 'Powodzie Moskwy jako wspólny skutek korupcji, wojennej presji i klimatu.',
    ('A2', 'asymetria-opcjonalnosci'): 'Ukraina zachowuje więcej możliwych ruchów; Rosja stopniowo zużywa własne opcje.',
    ('A2', 'cena-rezerwy-ua'): 'Przybliżony koszt utrzymywania ukraińskiej rezerwy strategicznej i swobody wyboru.',
    ('A2', 'rosja-wydala-opcje'): 'Rosja zużywa zasoby i swobodę działania na podtrzymywanie bieżącej presji.',
    ('A2', 'wniosek-systemowy'): 'Przewaga Ukrainy wynika z rosnącej opcjonalności przy kurczących się wyborach Rosji.',
    ('A2', 'sygnalizacja-i-asymetria'): 'Uderzenia jako komunikacja strategiczna oraz asymetria dostępnych opcji obu stron.',
    ('A2', 'timing-stala'): 'Rosyjskie ataki na cywilów są stałe; informację niesie wybrany moment riposty.',
    ('A2', 'oreshnik-klasa'): 'Rzadkie użycie Oreshnika jako sygnał rangi odpowiedzi, nie skuteczności rażenia.',
    ('A2', 'nie-mogla-nie-chciala'): 'Opóźniona odpowiedź: brak zasobów albo przesunięty próg reakcji Rosji.',
    ('A2', 'cztery-tryby'): 'Cztery modele relacji między intencją, działaniem i zniekształceniem informacji.',
    ('A2', 'oreshnik-komunikat'): 'Oreshnik jako osobny komunikat wewnątrz większego pakietu rakietowego.',
    ('A2', 'oreshnik-czas'): 'Czy pocisk jest ripostą za przeszłość, czy ostrzeżeniem wobec przyszłości.',
    ('A2', 'oreshnik-adresat'): 'Porównanie możliwych odbiorców; Europa jako hipoteza wiodąca.',
    ('A2', 'oreshnik-przechwyt'): 'Techniczna luka europejskiej obrony przed szybkim pociskiem z wieloma efektorami.',
    ('A2', 'oreshnik-szczebel'): 'Oreshnik jako pośredni szczebel między przemocą konwencjonalną a progiem nuklearnym.',
    ('A2', 'dwa-pociski'): 'Liczba dwóch pocisków rozpisana na trzy konkurencyjne interpretacje.',
    ('A2', 'odpowiedz-rosji'): 'Timing i Oreshnik jako klucze do odczytania rosyjskiej odpowiedzi na kampanię.',
    ('A2', 'predykcje-taktyczne-krotkoterminowe'): 'Krótkoterminowe, falsyfikowalne prognozy konkretnych zdarzeń i ich bieżące rozliczenie.',
    ('A2', 'predykcje-strukturalne'): 'Prognozy zmian stanu systemu, nie pojedynczych trafień.',
    ('A2', 'predykcje-zewnetrzne-zegary'): 'Niezależne zegary zewnętrzne do kalibracji tezy o jesieni 2026.',
    ('A2', 'predykcje-kampania-podstacji'): 'Hipoteza systematycznej kampanii na podstacje UES w lipcu–wrześniu 2026.',
    ('A2', 'podstacje-vs-elektrownie'): 'Podstacje jako słabiej bronione i trudniejsze do odtworzenia cele sieciowe.',
    ('A2', 'podstacje-tempo'): 'Dwutygodniowe tempo: adaptacja bez regeneracji i kontrola ryzyka kaskady.',
    ('A2', 'podstacje-maskowanie'): 'Podstacje ukrywane w pakietach innych celów i informacyjnym szumie kampanii.',
    ('A2', 'podstacje-brak-triggera'): 'Salami slicing uniemożliwia wskazanie pojedynczego wiarygodnego progu eskalacji.',
    ('A2', 'predykcje-projekcja-18-wrzesnia'): 'Nominalna projekcja skumulowanego deficytu UES po sześciu cyklach kampanii.',
    ('A2', 'predykcje-doktryna-syntetyczna'): 'Dziesięciopunktowy, falsyfikowalny manifest operacyjny predykcji P6.',
    ('A2', 'rejestr-predykcji'): 'Bieżące rozliczanie prognoz taktycznych, strukturalnych i doktrynalnych.',
    ('A2', 'audyt-nosorozce'): 'Status 24 nosorożców po dwóch miesiącach: co przyspieszyło, potwierdziło się lub czeka.',
    ('A2', 'audyt-bestiariusz-reszta'): 'Rewizja słonia, flamingów, łabędzi i tygrysów poza główną listą nosorożców.',
    ('A2', 'audyt-przeskok'): 'Miejsca, gdzie maj przesunął proces z prognozy do nowej jakościowej kategorii.',
    ('A2', 'audyt-zegary'): 'Niezależne wskaźniki czasowe zbiegające się wokół końca 2026.',
    ('A2', 'patrymonialny-grid-lock'): 'Sieci klientelistyczne tłumaczą stabilność reżimu mimo narastającego rozkładu.',
    ('A2', 'audyt-wniosek'): 'Kierunek Kolumbryny utrzymany, tempo szybsze; systemowego „suddenly” jeszcze nie ma.',
    ('A2', 'audyt-metareflexja-osint'): 'Znikanie danych i metryk jako samodzielny sygnał OSINT.',
    ('A2', 'audhd-detekcja-absencji'): 'Hipoteza związku profilu poznawczego z wyłapywaniem brakujących elementów wzorca.',
    ('A2', 'audyt-powtorzenie-bledu'): 'Instytucje powtarzają kosztowne błędy mimo jawnej wiedzy o ich skutkach.',
    ('A2', 'audyt-kolumbryny'): 'Konfrontacja marcowych hipotez Kolumbryny z danymi z maja i czerwca.',
    ('A2', 'rynek-chronologia'): 'Od pierwszych zakłóceń 2025 do reglamentacji paliwa w 2026.',
    ('A2', 'rynek-rafinerie'): 'Spadek przerobu przez seryjne wyłączenia i niszczenie rafinerii.',
    ('A2', 'rynek-import-bialorus'): 'Białoruski import łagodzi braki, lecz nie zastępuje utraconych mocy rosyjskich.',
    ('A2', 'rynek-rurociagi'): 'Przesył paliw ograniczany uderzeniami w pompownie i rurociągi.',
    ('A2', 'rynek-kolej'): 'Kolej przeciążona degradacją własną, wojną i dywersją.',
    ('A2', 'rynek-drogi'): 'Transport cysternami nie ma skali potrzebnej do zastąpienia kolei i rurociągów.',
    ('A2', 'rynek-magazyny'): 'Uderzenia w zbiorniki usuwają zapasy i buforowanie systemu paliwowego.',
    ('A2', 'rynek-stacje'): 'Kupony, kolejki i limity jako konsumencki finał kaskady paliwowej.',
    ('A2', 'rynek-paliw-siedem-brakow'): 'Siedem równoległych awarii od przerobu po detal tworzy strukturalny deficyt paliw.',
    ('A2', 'klimat-asymetria'): 'Rosyjska geografia i infrastruktura czynią koszt zmian klimatu szczególnie asymetrycznym.',
    ('A2', 'klimat-permafrost'): 'Topnienie zmarzliny jako wielobilionowy koszt dla infrastruktury i surowców.',
    ('A2', 'klimat-suppression-of-science'): 'Chilling effect po 2009–2012 odcina Rosję od własnej wiedzy klimatycznej.',
    ('A2', 'klimat-infrastruktura-na-gruncie'): 'Kolej, rurociągi i fundamenty destabilizowane przez różne typy degradującej zmarzliny.',
    ('A2', 'haldy-walbrzych-jako-analogia'): 'Płonące hałdy jako analogia fizyki ukrytego ognia w torfie i zmarzlinie.',
    ('A2', 'klimat-powodzie-susze-2025'): 'Susze, powodzie i pożary zmieniają mapę ryzyk infrastrukturalnych Rosji.',
    ('A2', 'klimat-kaskada-lato-2026'): 'Susza i upał ograniczają chłodzenie elektrowni i pogłębiają deficyt mocy.',
    ('A2', 'klimat-cascade-gradient'): 'Trzy ścieżki przełożenia klimatu na energię, logistykę i budżet.',
    ('A2', 'klimat-implikacje'): 'Klimat jako dodatkowy zegar przyspieszający wcześniejsze prognozy systemowe.',
    ('A2', 'matka-natura-nie-odpuszcza'): 'Klimat jako niezależny, narastający wektor presji na rosyjską infrastrukturę i finanse.',
    ('A2', 'energetyka-stranded-jamal'): 'Gaz Jamału traci wartość bez wystarczających dróg eksportu i przesyłu.',
    ('A2', 'energetyka-rankine-elektrownie'): 'Niski i ciepły przepływ rzek ogranicza chłodzenie elektrowni cieplnych i jądrowych.',
    ('A2', 'energetyka-aluminium-kanibalizm'): 'Deficyt prądu i surowców uderza w aluminium potrzebne rosyjskiej zbrojeniówce.',
    ('A2', 'energetyka-ues-topologia'): 'Siedem stref UES łączą zbyt wąskie korytarze przesyłowe.',
    ('A2', 'energetyka-import-awaryjny'): 'Rosyjska sieć ma znikomą możliwość awaryjnego importu energii z sąsiadów.',
    ('A2', 'energetyka-grid-okupowany'): 'Uderzenia w grid okupowany stopniowo odcinają Krym i zaplecze wojskowe.',
    ('A2', 'energetyka-sztywnosc-kierunkowa'): 'Dużo infrastruktury nie oznacza redundancji, gdy przepływy są kierunkowo sztywne.',
    ('A2', 'energetyka-synteza'): 'Klimat i topologia same mogą doprowadzić UES do chronicznych niedoborów.',
    ('A2', 'energetyka-siec-bez-redundancji'): 'Fizyka, topologia i sankcje odsłaniają kruchość rosyjskiego systemu energetycznego.',
    ('A2', 'skorowidz-ukraina-polityka'): 'Najważniejsi ukraińscy politycy i przedstawiciele wywiadu występujący w analizie.',
    ('A2', 'skorowidz-ukraina-wojsko'): 'Ukraińscy dowódcy operacyjni i ich role w opisywanych kampaniach.',
    ('A2', 'skorowidz-rosja-wladza'): 'Rosyjscy decydenci centralni i regionalni przywoływani w dokumencie.',
    ('A2', 'skorowidz-zachod'): 'Zachodni politycy, dyplomaci i przedstawiciele służb cytowani w analizie.',
    ('A2', 'skorowidz-region'): 'Aktorzy regionalni z Azerbejdżanu, Białorusi i kanałów mediacyjnych.',
    ('A2', 'skorowidz-osint'): 'Analitycy, dziennikarze i źródła OSINT używane w dokumencie.',
    ('A2', 'skorowidz-nauka'): 'Badacze i eksperci dostarczający danych oraz ram naukowych.',
    ('A2', 'skorowidz-kultura'): 'Postacie historyczne i kulturowe używane jako punkty odniesienia.',
    ('A2', 'skorowidz-ludzi'): 'Indeks osób i ról potrzebnych do orientacji w długim dokumencie.',
    ('A2', 'motyw-literacki'): 'Ukrywanie kluczowego działania przez zalew innych zdarzeń i bodźców.',
    ('A2', 'motyw-doktrynalny-historia'): 'Maskirowka od praktyki sowieckiej do współczesnej rosyjskiej wojny informacyjnej.',
    ('A2', 'motyw-strukturalna-slepota'): 'Kreml nie rozpoznaje odwróconej wobec siebie techniki, którą sam historycznie stosował.',
    ('A2', 'motyw-dynamika-iiws'): 'Analogie do Bagrationu i kampanii naftowej jako zespolenia wielu instrumentów presji.',
    ('A2', 'motyw-doktrynalny'): 'Rosyjski wzorzec maskirowki odwrócony i zastosowany przeciw jego twórcy.',
    ('A2', 'zrodla-prasa-instytucje'): 'Media, agencje i instytucje analityczne używane do weryfikacji zdarzeń.',
    ('A2', 'zrodla-telegram-osint'): 'Telegramowe kanały OSINT dostarczające danych z Rosji, Ukrainy i Krymu.',
    ('A2', 'zrodla-satelita'): 'Dane satelitarne i termiczne do niezależnej weryfikacji skutków uderzeń.',
    ('A2', 'zrodla-bluesky-x'): 'Analitycy i konta OSINT na Bluesky oraz X.',
    ('A2', 'zrodla-ramy-interpretacyjne'): 'Horbyk, Douglas i Mottron jako źródła głównych ram interpretacyjnych.',
    ('A2', 'zrodla-dokumentu'): 'Zestaw źródeł medialnych, OSINT, satelitarnych i akademickich.',
    ('A2', 'gradually-stalo-sie-suddenly'): 'Aktualizowana analiza przejścia rosyjskiego systemu od narastającej degradacji do zmian jakościowych. Łączy uderzenia, logistykę, energię, politykę i kalibrację prognoz.',
    ('A3', 'lista-celow'): 'Chronologiczny rejestr strategicznych uderzeń od stycznia do czerwca 2026: cele, skutki, zasięg i zmieniający się rytm kampanii.',
    ('A3', 'lista-uderzen'): 'Uderzenia uporządkowane okresami, z klasyfikacją celów, skutków i frontów.',
    ('A3', 'lista-wstep'): 'Kluczowe daty, zasady klasyfikacji, statusy uszkodzeń i statystyki bazowe.',
    ('A3', 'okres-1'): 'Rejestr uderzeń 4–17 stycznia: początkowa, rzadka faza kampanii.',
    ('A3', 'okres-2'): 'Rejestr uderzeń 18–31 stycznia: powrót rafinerii i pierwsze zagęszczenie celów.',
    ('A3', 'okres-3'): 'Rejestr uderzeń 1–14 lutego: Wołgograd i skok zasięgu do głębokiego zaplecza.',
    ('A3', 'okres-4'): 'Rejestr uderzeń 15–28 lutego: spowolnienie zakończone wybuchem wojny w Iranie.',
    ('A3', 'okres-4-paradoks-hormuz'): 'Start paradoksu Hormuz: wojna w Iranie chwilowo podnosi rosyjskie przychody naftowe.',
    ('A3', 'okres-5'): 'Rejestr uderzeń 1–14 marca: elektronika, gaz i dobór precyzyjniejszej amunicji.',
    ('A3', 'okres-6'): 'Rejestr uderzeń 15–28 marca: dywersyfikacja na Bałtyk, Powołże, chemię i lotnictwo.',
    ('A3', 'okres-7'): 'Rejestr uderzeń 29 marca–11 kwietnia: selektywna pauza, nie pełne wstrzymanie.',
    ('A3', 'okres-7-korekta-pauza'): 'Wielkanocna pauza dotyczyła wybranych klas celów, nie całej kampanii.',
    ('A3', 'okres-8'): 'Rejestr uderzeń 12–25 kwietnia: Morze Czarne, Baszkortostan i kompresja cyklu napraw.',
    ('A3', 'okres-9'): 'Rejestr uderzeń 26 kwietnia–9 maja: głębia Rosji, Bałtyk i nowe węzły produkcyjne.',
    ('A3', 'okres-10'): 'Rejestr uderzeń 10–16 maja: demembranizacja perymetru Moskwy i dalsza kompresja rafinerii.',
    ('A3', 'okres-10-nota-rytm'): 'Tempo zdarzeń wymusza przejście rejestru z okresów dwutygodniowych na tygodniowe.',
    ('A3', 'okres-11'): 'Rejestr 17–23 maja: uderzenia połączone z kampanią komunikacyjną i sygnalizacją.',
    ('A3', 'okres-11-trzydniowa-kampania'): 'Zsynchronizowana warstwa komunikacyjna 17–18 maja nad kampanią kinetyczną.',
    ('A3', 'okres-12'): 'Rejestr 24–30 maja: kulminacja uderzeń głębokich i formalizacja „long-range sanctions”.',
    ('A3', 'okres-12-pakiet-2705'): '27 maja: największy dotąd pakiet równoległych uderzeń głębokich.',
    ('A3', 'statystyki-maja-syrski'): 'Oficjalny bilans ZSU za maj: cele Deep Strike, straty, terytorium i obrona powietrzna.',
    ('A3', 'okres-13'): 'Rejestr 31 maja–6 czerwca: SPIEF, Bałtyk, Krym i rozszerzenie kampanii do około 1000 km.',
    ('A3', 'okres-13-spief'): 'Uderzenie w Petersburg w dniu otwarcia SPIEF jako czysta sygnalizacja kalendarzem.',
    ('A3', 'okres-14'): 'Rejestr 7–13 czerwca: interdykcja R-280, podstacje, kolej, arsenały i nowe typy celów.',
    ('A3', 'okres-15'): 'Rejestr 14–20 czerwca: dalsza presja na paliwa, Moskwę, Krym i infrastrukturę.',
    ('A3', 'okres-16'): 'Rejestr od 21 czerwca: Krym jako wyspa, mikroelektronika, rafinerie i krajowa kaskada paliwowa.',
}

with SRC.open('r', encoding='utf-8', newline='') as f:
    rows = list(csv.DictReader(f, delimiter='\t'))
seen = set()
out_rows = []
for row in rows:
    code = row['dokument_kod']
    if code == 'A1':
        continue
    key = (code, row['anchor'])
    if key not in MANUAL:
        continue
    if key in seen:
        raise SystemExit(f'STOP: duplicate key in source map: {key}')
    seen.add(key)
    row = dict(row)
    row['opis'] = MANUAL[key]
    out_rows.append(row)
missing = set(MANUAL) - seen
if missing:
    raise SystemExit(f'STOP: manual descriptions not found in source map: {sorted(missing)}')
fieldnames = list(rows[0].keys()) + ['opis']
with OUT.open('w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t', lineterminator='\n')
    w.writeheader()
    w.writerows(out_rows)
print(f'OK: zapisano {len(out_rows)} recznych opisow; A1 pominiete')
